#!/usr/bin/env node

// commander stuff
var program = require('commander');
var util = require('util');

console.log('-------------------------------------------');
console.log('  ScrAPI - expose a website as a REST API');
console.log('-------------------------------------------');
program
.version('0.0.1')
.usage('[options] <config file>')
.option('-d, --document', 'Generate documentation of API')
.parse(process.argv);

// if no config file, exit
if (program.args[0] === undefined) {
  program.help();
}

// load templates for code generation
var templateDir = './templates';
// default file to save to
var outputFile = "app.js";

fs = require('fs')

// API method template
var APIMethod = fs.readFileSync(templateDir + '/APIMethod.js').toString();
// includes template
var includes = fs.readFileSync(templateDir + '/includes.js').toString();
// server start template
var serverstart = fs.readFileSync(templateDir + '/serverstart.js').toString();

// load config
var Config = JSON.parse(fs.readFileSync(program.args[0]).toString());
// TODO: validate Config 

console.log('Creating app.js...');

// app is divided into three sections
// Section 1: header - the include libraries
var app = includes;

// Section 2: each method defined in the config
for (var method in Config.methods) {
	console.log(util.inspect(method));
  app += APIMethod.replace('%%URI%%', method)
  				  .replace('%%OPTIONS%%', JSON.stringify(Config.methods[method]))
  				  .replace('%%SYNOPSIS%%', Config.methods[method].doc_synopsis);
}

// Section 3: some code to start the express webserver
app += serverstart.replace("%%PORT%%", Config.port)

// if (fs.existsSync(outputFile)) {
  // program.prompt('File exists, overwrite? [y/N]: ', function(choice){
  //     if (choice.toLowerCase() === 'y') {
    fs.writeFile(outputFile, app);
  //     }
  // });
// }

